eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 10101
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:BestWishes/engineConfig.git
          default-label: master
