server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka
#  cloud:
#    stream:
#      kafka:
#        binder:
#          zk-nodes: 127.0.0.1:2181
#          brokers: 127.0.0.1:9092
#management:
#  security:
#    enabled: false